#server.port=8186
#
#using.spring.schedulerFactory=true
#
#spring.quartz.job-store-type=jdbc
## Always create the Quartz database on startup
#spring.quartz.jdbc.initialize-schema=never
#
#spring.datasource.jdbc-url=jdbc:sqlserver://192.168.31.35:1433;databaseName=MAILHR;encrypt=false;trustServerCertificate=true;
#spring.datasource.username=MAILHR
#spring.datasource.password=Vieta2023
##spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
##spring.jpa.show-sql=true
##spring.jpa.hibernate.ddl-auto = create-drop
##spring.jpa.properties.dialect = org.hibernate.dialect.SQLServer2012Dialect
#
### MailProperties
#spring.mail.host=192.168.31.44
#spring.mail.port=587
#spring.mail.username=ebanking@mail.vab.local
#spring.mail.password=Eb@nk2019
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.smtp.ssl.trust=*
#
#
#cron=*/30 * * * * ?
#mail.cc1="phuonglv@vietabank.com.vn
#mail.cc2="chinhtt@vietabank.com.vn
#mobile.cc1=0983754311
#mobile.cc2=0902179466