# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
server.port=8185
using.spring.schedulerFactory=true
spring.quartz.job-store-type=jdbc
# Always create the Quartz database on startup
spring.quartz.jdbc.initialize-schema=never
#
#logfile.path=/home/phuonglv/logback.xml
logfile.path=D:\\NGAN_HANG_DIEN_TU\\EBANK_TEST\\hr-automail\\src\\main\\resources\\logger.xml
#
#spring.datasource.jdbc-url=jdbc:sqlserver://192.168.31.35:1433;databaseName=MAILHR;encrypt=false;trustServerCertificate=true;
#spring.datasource.username=MAILHR
#spring.datasource.password=Vieta2023
#spring.datasource.url=jdbc:oracle:thin:@//192.168.31.49:1521/testora19c
spring.datasource.jdbc-url=jdbc:oracle:thin:@//192.168.31.49:1521/testora19c
spring.datasource.username=EMAILNHACNO
spring.datasource.password=Vieta2024#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto = create-drop
#spring.jpa.properties.dialect = org.hibernate.dialect.SQLServer2012Dialect


#RabbitMQ
#spring.rabbitmq.host=192.168.31.13
#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672

#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest
#spring.rabbitmq.virtual-host=/
#spring.rabbitmq.connection-timeout=300000
#spring.rabbitmq.requested-heartbeat=60
#logging.level.org.springframework.amqp=DEBUG
#logging.level.com.rabbitmq.client=DEBUG
spring.rabbitmq.template.reply-timeout=5000
spring.rabbitmq.listener.direct.auto-startup=true


## MailProperties
#spring.mail.host=mta.vietabank.com.vn
#spring.mail.port=587
#spring.mail.username=vabinsider@vietabank.com.vn
#spring.mail.password=x7%@&L!zN599Kf7L
# e
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
#spring.mail.properties.mail.smtp.ssl.trust=*
#spring.mail.debug=true
### MailProperties
#spring.mail.host=192.168.31.44
#spring.mail.port=25
#spring.mail.username=ebanking@mail.vab.local
#spring.mail.password=Eb@nk2019
spring.mail.host=192.168.31.143
spring.mail.port=587
spring.mail.username=test5@vabtest.local
spring.mail.password=Vab@1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.debug=true
#cron=0 54 16 ? * *
#cron-birthday=0 05 16 * * ?
#cron-onboard=0 10 16 * * ?
cron-birthday=0 34 9 ? * *
cron-onboard=0 12 15 ? * *
#email.cc=hoangnn@vietabank.com.vn,chinl1@vietabank.com.vn,huyenntt8@vietabank.com.vn
email.cc=phuonglv@vietabank.com.vn
#mobile.cc=0902179466,0829323774,0976868713
mobile.cc=0983754311
email.bcc=vabinsider-onms@vietabank.com.vn
sms.content=He thong khong the gui thu chuc mung ky niem onboard. Admin vui long kiem tra nguyen nhan va thong bao Khoi QTNNL gui mail thu cong.
sms.url=http://192.168.31.215:8181/HRAutoMailService/CallSMSGateway
sms.Accesskey=HRAutoMail
sms.Signature=HRAutoMail