# thread-pool
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount=2
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true

# job-store
# Enable this property for RAMJobStore
org.quartz.jobStore.class=org.quartz.simpl.RAMJobStore

# Enable these properties for a JDBCJobStore using JobStoreTX
#org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
#org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.MSSQLDelegate
#org.quartz.jobStore.dataSource=quartzDataSource
# Enable this property for JobStoreCMT
#org.quartz.jobStore.nonManagedTXDataSource=quartzDataSource

# H2 database
# use an in-memory database & initialise Quartz using their standard SQL script
#org.quartz.dataSource.quartzDataSource.URL=jdbc:sqlserver://192.168.31.35;databaseName=MAILHR
#org.quartz.dataSource.quartzDataSource.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
#org.quartz.dataSource.quartzDataSource.user=MAILHR
#org.quartz.dataSource.quartzDataSource.password=Vieta2023
#org.quartz.jdbc.initialize-schema=always
